---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/tags/app-template-4.2.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app graylog-mongodb
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            image:
              repository: mongo
              tag: 8.0.15@sha256:d0d76261e7a19aee701e890a9e835ba369a12b8733e7d39cd89a923ed97f247c
              pullPolicy: IfNotPresent
    service:
      main:
        controller: main
        ports:
          http:
            port: 27017
    persistence:
      data:
        existingClaim: graylog-mongodb
        advancedMounts:
          main:
            main:
              - path: /data/db
